[build]
buildCommand = "cd confession_project && pip install -r ../requirements.txt && python manage.py migrate"

[start]
startCommand = "cd confession_project && python manage.py runserver 0.0.0.0:8000"
